SET NAMES utf8mb4;

-- Performance metrics introduced here are exact only from rollout onward.
-- No historical Activity creator, record view, active-time, or closed_at values are inferred.

ALTER TABLE users
  MODIFY COLUMN role ENUM('admin','sales','support','operations') NOT NULL DEFAULT 'sales';

ALTER TABLE activities
  ADD COLUMN created_by_user_id INT UNSIGNED NULL AFTER owner_user_id,
  ADD INDEX idx_activities_created_by (created_by_user_id, created_at),
  ADD CONSTRAINT fk_activities_created_by
    FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE record_view_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  entity_type VARCHAR(40) NOT NULL,
  entity_id INT UNSIGNED NOT NULL,
  viewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_address VARCHAR(64) NULL,
  INDEX idx_record_views_user_time (user_id, viewed_at),
  INDEX idx_record_views_entity (entity_type, entity_id),
  INDEX idx_record_views_unique_metric (user_id, entity_type, entity_id, viewed_at),
  CONSTRAINT fk_record_views_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE user_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  session_token_hash CHAR(64) NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended_at DATETIME NULL,
  active_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_sessions_token (session_token_hash),
  INDEX idx_user_sessions_user_started (user_id, started_at),
  INDEX idx_user_sessions_user_last_seen (user_id, last_seen_at),
  CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

ALTER TABLE tickets
  ADD COLUMN origin_type ENUM('contact','user','system') NULL AFTER assigned_user_id,
  ADD COLUMN closed_at DATETIME NULL AFTER origin_type,
  ADD INDEX idx_tickets_origin_created (origin_type, created_at),
  ADD INDEX idx_tickets_closed_at (closed_at);

-- Activation requests are system-generated by a stable application workflow.
UPDATE tickets
SET origin_type = 'system'
WHERE origin_type IS NULL
  AND subject = 'درخواست فعال‌سازی حساب کاربری مخاطب';

-- Reliable backfill only: classify remaining records from the earliest persisted message.
UPDATE tickets t
LEFT JOIN (
  SELECT tm.ticket_id, tm.sender_type
  FROM ticket_messages tm
  INNER JOIN (
    SELECT ticket_id, MIN(id) AS first_message_id
    FROM ticket_messages
    GROUP BY ticket_id
  ) first_message ON first_message.first_message_id = tm.id
) first_sender ON first_sender.ticket_id = t.id
SET t.origin_type = CASE
  WHEN first_sender.sender_type = 'contact' THEN 'contact'
  WHEN first_sender.sender_type = 'user' THEN 'user'
  ELSE NULL
END
WHERE t.origin_type IS NULL;

CREATE TABLE ticket_status_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ticket_id INT UNSIGNED NOT NULL,
  from_status VARCHAR(80) NOT NULL,
  to_status VARCHAR(80) NOT NULL,
  changed_by_type ENUM('user','contact','system') NOT NULL,
  changed_by_user_id INT UNSIGNED NULL,
  changed_by_contact_id INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ticket_status_events_ticket_time (ticket_id, created_at),
  INDEX idx_ticket_status_events_user_time (changed_by_user_id, created_at),
  CONSTRAINT fk_ticket_status_events_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_ticket_status_events_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ticket_status_events_contact FOREIGN KEY (changed_by_contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB;
